CREATE TABLE IF NOT EXISTS users
(
    user_id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email varchar(64) NOT NULL,
    login varchar(64) NOT NULL,
    name varchar(64),
    birthday date
);

CREATE TABLE IF NOT EXISTS film
(
    film_id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name varchar(64) NOT NULL,
    description varchar(128) NOT NULL,
    release_date date,
    duration int,
    rate int,
    rating ENUM('G', 'PG', 'PG-13', 'R', 'NC-17')
);

CREATE TABLE IF NOT EXISTS user_friend
(
    user_id int REFERENCES users (user_id),
    friend_id int REFERENCES users (user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id int REFERENCES film (film_id),
    user_id int REFERENCES users (user_id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id int generated by default as identity PRIMARY KEY,
    name varchar(64)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id int REFERENCES film (film_id),
    genre_id int REFERENCES genre (genre_id),
    PRIMARY KEY (film_id, genre_id)
);